library(qtl2)
library(qtl2convert)




### Read in genoprobs generated by Dan Gatti. Edit to keep only DO2 mice and remove duplicates
# Data are in /projects/churchill-lab/data/Weinstock/Pomp_Benson/genotypes/
genoprobs <- readRDS("~/Desktop/Weinstock Pomp Microbiome/Genotypes/Old/pomp_genoprobs_qtl2.rds")
map <- readRDS("~/Desktop/Weinstock Pomp Microbiome/Genotypes/Old/pomp_map_qtl2.rds")




genoprobs <- probs_qtl2_to_doqtl(genoprobs)
genoprobs <- genoprobs[grep('DO2', dimnames(genoprobs)[[1]]),,]
dimnames(genoprobs)[[1]] <- gsub('DPDP.', '', dimnames(genoprobs)[[1]], fixed = TRUE)
dimnames(genoprobs)[[1]] <- gsub('.F', '', dimnames(genoprobs)[[1]], fixed = TRUE)
dimnames(genoprobs)[[1]] <- gsub('.', '-', dimnames(genoprobs)[[1]], fixed = TRUE)










### Qtl2 format
markers <- map_list_to_df(map_list = map)
genoprobs <- probs_doqtl_to_qtl2(probs = genoprobs, map = markers, pos_column = 'pos')
K <- calc_kinship(probs = genoprobs, type = 'loco', cores = 0)











### Save
save.image("~/Desktop/Weinstock Pomp Microbiome/Genotypes/Old/weinstock_pomp_genoprobs_map_markers_K.RData")
